name: Build e Release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

permissions:
  contents: write

jobs:

  # ============================================================
  # WINDOWS
  # ============================================================

  windows:

    name: Gerar EXE Windows
    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Dar permissao gradle
        run: chmod +x gradlew
        shell: bash

      - name: Build EXE
        run: .\gradlew.bat clean buildWindowsExe

      - name: Listar arquivos
        run: dir dist

      - name: Upload EXE Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.exe
            scripts/instalar-windows.bat
            scripts/controle-horas.ico

  # ============================================================
  # LINUX
  # ============================================================

  linux:

    name: Gerar App Linux
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Permissao gradle
        run: chmod +x gradlew

      - name: Build Linux
        run: ./gradlew clean buildLinuxApp

      - name: Compactar Linux
        run: tar -czf controle-horas-linux.tar.gz dist/

      - name: Upload Linux Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            controle-horas-linux.tar.gz
            scripts/instalar-linux.sh
            scripts/desinstalar-linux.sh
            scripts/controle-horas.png

  # ============================================================
  # JAR
  # ============================================================

  jar:

    name: Gerar JAR
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Permissao Gradle
        run: chmod +x gradlew

      - name: Gerar JAR
        run: ./gradlew clean bootJar

      - name: Renomear JAR
        run: |
          cp build/libs/*.jar build/libs/controle-horas.jar

      - name: Upload JAR
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/controle-horas.jar